config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'recipes#index'
  resources :recipes do
    collection do
      get 'match'
      get 'search'
      post 'content'
    end
  end
  resources :ingredients, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients, dependent: :destroy
  has_many :recipes, through: :recipe_ingredients
  has_many :quantities


  def self.search(search)
    Ingredient.where('ingredient_name LIKE(?)', "%#{search}%") if search != ''
  end
end

app/models/quantity.rb
class Quantity < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many  :recipe_ingredients, dependent: :destroy
  has_many  :ingredients, through: :recipe_ingredients
  has_many  :quantities, dependent: :destroy
  has_one_attached :image 


  def self.search(search)
    Recipe.where('name LIKE(?)', "%#{search}%") if search != ''
  end
end

app/models/recipe_form.rb
class RecipeForm
  include ActiveModel::Model

  attr_accessor :name, :description, :ingredient_names, :quantities, :id, :image, :user_id

  with_options presence: true do
    validates :name
    validates :description
    validates :ingredient_name
    validates :quantity
  end

  def initialize(attribute = {})
    if !(attribute[:id] == nil)
      @recipe = Recipe.find(attribute[:id])
      @ingredients = @recipe.ingredients
      @quantity = @recipe.quantities
      @recipe_ingredients = @recipe.recipe_ingredients
      if attribute[:name] == nil
        self.id = @recipe.id
        self.name = @recipe.name
        self.description = @recipe.description
        if @recipe.image.present?
          self.image = @recipe.image
        end
        self.ingredient_names = []
        self.quantities = []
        @ingredients.each_with_index do |ingredient, i|
          self.ingredient_names << ingredient.ingredient_name
          self.quantities << @quantity[i].quantity
        end
      else
        self.id = attribute[:id]
        self.name = attribute[:name]
        self.description = attribute[:description]
        self.ingredient_names = attribute[:ingredient_names]
        self.quantities = attribute[:quantities]
        if attribute[:image].present?
          self.image = attribute[:image]
        end
      end
    else
      super(attribute)
    end
  end

  def save
    if self.image.present?
      recipe = Recipe.create(name: name, description: description, image: image ,user_id: user_id)
    else
      recipe = Recipe.create(name: name, description: description, user_id: user_id)
    end
    number = 0
    
    ingredient_names.each do |ingredient_name|
      ingredient = Ingredient.where(ingredient_name: ingredient_name).first_or_initialize
      ingredient.save
      Quantity.create(quantity: quantities[number],recipe_id: recipe.id, ingredient_id: ingredient.id)
      RecipeIngredient.create(recipe_id: recipe.id, ingredient_id: ingredient.id)
      number += 1
    end
  end

  def update
    if self.image.present?
      @recipe.update(name: name, image: image, description: description)
    else
      @recipe.update(name: name, description: description)
    end
    @ingredients.each_with_index do |ingredient, i|
      ingredient = Ingredient.where(ingredient_name: ingredient_names[i]).first_or_initialize
      ingredient.update(ingredient_name: ingredient.ingredient_name)
      @quantity[i].update(quantity: quantities[i], recipe_id: @recipe.id, ingredient_id: ingredient.id)
      @recipe_ingredients[i].update(recipe_id: @recipe.id, ingredient_id: ingredient.id)
    end
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze

  validates :email, uniqueness: { case_sensitive: true }
  validates_format_of :password, with: PASSWORD_REGEX, message: 'include both letters and numbers'
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :authenticate_user!

  def new
    @ingredient = Ingredient.new
  end

  def create
    @recipe = Recipe.new
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient = Ingredient.where(ingredient_name: @ingredient.ingredient_name).first_or_initialize
    if @ingredient.valid?
      @ingredient.save
      redirect_to new_recipe_path
    else
      render :new
    end
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:ingredient_name)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_recipe, only: %i[edit show update destroy]
  before_action :set_ingredients, only: %i[edit new content]
  before_action :move_to_index, only: %i[edit destroy update]

  def index
    @recipes = Recipe.includes(:user).order("created_at DESC")
  end

  def new
    @recipe = RecipeForm.new
  end

  def create
    @recipe = RecipeForm.new(recipe_params)
    if @recipe.save
      redirect_to root_path
    else
      render :content
    end
  end

  def content
    @recipe = RecipeForm.new(recipe_params)
  end

  def show; end

  def edit
    if params[:recipe_form].present?
      @recipe = RecipeForm.new(recipe_params.merge(id: params[:id]))
    else
      @recipe = RecipeForm.new(id: params[:id])
    end
  end

  def update
    @recipe = RecipeForm.new(recipe_params.merge(id: params[:id]))
    if @recipe.update
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @recipe.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def match
    return nil if params[:keyword] == ''

    ingredient = Ingredient.where(['ingredient_name LIKE ?', "%#{params[:keyword]}%"]) 
    
    render json: { keyword: ingredient }
  end

  def search
    @ingredients = Ingredient.search(params[:keyword])
    @recipes = Recipe.search(params[:keyword])
    @results = []
    
    @ingredients.each do |ingredient|
      ingredient.recipes.each do |recipe|
        @results << recipe
      end
    end

    @recipes.each do |recipe|
      @results << recipe
    end
    
    @results = @results.uniq
  end

  private

  def recipe_params
    params.require(:recipe_form).permit(:name, :description, :image, ingredient_names:[], quantities: []).merge(user_id: current_user.id)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def move_to_index
    redirect_to root_path unless @recipe.user.id == current_user.id
  end

  def set_ingredients
    @ingredients = Ingredient.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ingredients/new.html.erb
<%= form_with model: @ingredient, class: 'registration-main', local: true do |f| %>

  <div class='form-wrap'>
    <div class='form-header'>
      <h1 class='form-header-text'>
        食材登録
      </h1>
    </div>

    <%= render 'shared/error_messages', model: f.object %>  

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">食材名</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :ingredient_name, class:"input-default", id:"ingredient_name", placeholder:"食材名を入力してください", maxlength:"40" %>
    </div>

    <div class="form-group">
    </div>

    <div class='register-btn'>
      <%= f.submit "レシピ登録" ,class:"register-red-btn" %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeRator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/content.html.erb
<%= render "shared/header"%>

<div class="registration-main new">
  <div class='form-wrap new'>
    <div class='form-header'>
      <h1 class='form-header-text'>
        <%= @recipe.name %>
      </h1>
    </div>
    <%# <%= form_with model: @recipe, url: content_recipes_path, method: :post, id:"image-post", local: true do |f| %>
      <%# <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">イメージ</label>
          <span class="indispensable">クリックして保存する</span>
        </div>
          <label class="form-image">
            <%= f.file_field :image , class:"hide"%>
          <%# </label>
      </div> 
    <% end %> 

    <%= form_with model: @recipe, url:recipes_path, method: :post , id:"main-form", local: true do |f| %>
      <%= f.text_area :name, class:"input-default hide", id:"name", placeholder:"食材名を入力してください", maxlength:"40" %>
      <%= render 'shared/error_messages', model: @recipe %>  
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">イメージ</label>
        </div>
        <label class="form-image">
          <%= f.file_field :image %>
        </label>
      </div> 
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">材料</label>
        </div>
        <div class="ingredients" id="ingredient-index">
          <div class="ingredient-content">
            <% if @recipe.ingredient_names != [""] && @recipe.ingredient_names.present? %>
              <div class="ingredient-lists">
                <% @recipe.ingredient_names.each_with_index do |ingredient, i|%>
                  <div class="ingredient-row">
                    <p class="ingredient-name"><%= ingredient %></p>
                    <p class="ingredient-quantitiy"><%= @recipe.quantities[i] %></p>
                  </div>
                <% end %>
              </div> 
            <% else %>
              <div class="ingredient-lists">
                <div class="ingredient-row">
                  <p class="ingredient-name">食材を入力してください</p>
                  <p class="ingredient-quantitiy">量を入力してください</p>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div> 
      <div class="hidden">
        <% if @recipe.ingredient_names != [""] && @recipe.ingredient_names.present? %>
          <% @recipe.ingredient_names.each_with_index do |ingredient, i| %>
            <div class="ingredient-group ingredient-form">
              <input type="text" name="recipe_form[ingredient_names][]", value="<%= ingredient %>", placeholder="食材・調味料", class="input-ingredient input", id="ingredient_name">
              <input type="text" name="recipe_form[quantities][]", value="<%= @recipe.quantities[i] %>" , placeholder="分量", class="input-ingredient input", id="quantitity">
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">レシピ説明</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"input-recipe", id:"password", placeholder:"レシピ説明" ,rows: "10"%>
      </div>

      <div class="form-group">
      </div>

      <div class='register-btn'>
        <%= f.submit "レシピ登録" ,class:"register-red-btn" %>
      </div>
  
    <% end %>
  </div>
</div >

<!-- レイヤー -->
<div id="layer"></div>
<!-- ポップアップ -->
<div id="popup">
  <div class="popup-box">
    <%= form_with model: @recipe, url: content_recipes_path, method: :post, class: 'popup-main', id:"form", local: true do |f| %>
      <%= f.text_area :name, class:"input-default hide", id:"name", placeholder:"食材名を入力してください", maxlength:"40" %>
      <div class="popup-wrap">
        <div class="popup-form"> 
          <div class="ingredient-group">
            <div class='ingredient-wrap'>
              <label class="form-text">食材・調味料</label>
            </div>
            <div class='ingredient-wrap'>
              <label class="form-text">分量</label>
            </div>
          </div>
            <% if @recipe.ingredient_names != [""] && @recipe.ingredient_names.present? %>
              <% @recipe.ingredient_names.each_with_index do |ingredient, i| %>
                <div class="ingredient-group ingredient-form">
                  <input type="text" name="recipe_form[ingredient_names][]", value="<%= ingredient %>", placeholder="食材・調味料", class="input-ingredient input", id="ingredient_name">
                  <input type="text" name="recipe_form[quantities][]", value="<%= @recipe.quantities[i] %>" , placeholder="分量", class="input-ingredient input", id="quantitity">
                </div>
              <% end %>
            <% else %>
              <div class="ingredient-group ingredient-form">
                <input type="text" name="recipe_form[ingredient_names][]", placeholder="食材・調味料", class="input-ingredient input", id="ingredient_name">
                <input type="text" name="recipe_form[quantities][]", placeholder="分量", class="input-ingredient input", id="quantitity">
              </div>
            <% end %>

          <%# 追加・削除をするためのフォームをJSで扱えるようにする %>
          <%= javascript_tag  do %>
            const ingredient =  
            `  <div class="ingredient-group ingredient-form">
            <input type="text" name="recipe_form[ingredient_names][]", placeholder="食材・調味料", class="input-ingredient input", id="ingredient_name">
            <input type="text" name="recipe_form[quantities][]", placeholder="分量", class="input-ingredient input", id="quantitity">
          </div>`
          <% end %>
          <div class="button-wrap">
            <button type="button" class="ingredient-button" id="button_plus">行を追加</button>
            <button type="button" class="ingredient-button" id="button_delete">行を削除</button>
          </div>
          
        </div>
        <%= f.submit "保存して閉じる" ,class:"popup-register-btn", id:"save"%>
        <button type="button" class="batsu" id="close">×</button>
      </div>
    <% end %>
  </div>  
</div>


<%= render "shared/footer"%>

app/views/recipes/edit.html.erb
<%= render "shared/header"%>
<%= form_with model: @recipe, url: recipe_path, method: :put,class: 'registration-main', local: true do |f| %>

<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      レシピ登録
    </h1>
  </div>

  <%= render 'shared/error_messages', model: f.object %>  

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">レシピ名</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :name, class:"input-default", id:"name", placeholder:"レシピ名を入力してください", maxlength:"40" %>
  </div> 
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">イメージ</label>
    </div>
     <label class="form-image">
      <%= f.file_field :image %>
    </label>
  </div> 

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">材料</label>
    </div>
    <div class="ingredients" id="ingredient-index">
      <div class="ingredient-content">
        <% if @recipe.ingredient_names != [""] && @recipe.ingredient_names.present? %>
          <div class="ingredient-lists">
            <% @recipe.ingredient_names.each_with_index do |ingredient, i|%>
              <div class="ingredient-row">
                <p class="ingredient-name"><%= ingredient %></p>
                <p class="ingredient-quantitiy"><%= @recipe.quantities[i] %></p>
              </div>
            <% end %>
          </div> 
        <% else %>
          <div class="ingredient-lists">
            <div class="ingredient-row">
              <p class="ingredient-name">食材を入力してください</p>
              <p class="ingredient-quantitiy">量を入力してください</p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div> 
  <div class="hidden">
    <% if @recipe.ingredient_names != [""] && @recipe.ingredient_names.present? %>
      <% @recipe.ingredient_names.each_with_index do |ingredient, i| %>
        <div class="ingredient-group ingredient-form">
          <input type="text" name="recipe_form[ingredient_names][]", value="<%= ingredient %>", placeholder="食材・調味料", class="input-ingredient input", id="ingredient_name">
          <input type="text" name="recipe_form[quantities][]", value="<%= @recipe.quantities[i] %>" , placeholder="分量", class="input-ingredient input", id="quantitity">
        </div>
      <% end %>
    <% end %>
  </div>


  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">レシピ説明</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :description, class:"input-recipe", id:"password", placeholder:"レシピ説明" ,rows: "10"%>
  </div>

  <div class="form-group">
  </div>

  <div class='register-btn'>
    <%= f.submit "レシピ登録" ,class:"register-red-btn" %>
  </div>
</div>
<% end %>


<!-- レイヤー -->
<div id="layer"></div>
<!-- ポップアップ -->
<div id="popup">
  <div class="popup-box">
    <%= form_with model: @recipe, url: edit_recipe_path(@recipe.id), method: :get, class: 'popup-main', id:"form", local: true do |f| %>
      <%= f.text_area :name, class:"input-default hide", id:"name", placeholder:"食材名を入力してください", maxlength:"40" %>
      <%= f.text_area :description, class:"input-recipe hide", id:"password", placeholder:"レシピ説明" ,rows: "10"%>
      <%= f.file_field :image,class:"input-recipe hide" %>
      <div class="popup-wrap">
        <div class="popup-form"> 
          <div class="ingredient-group">
            <div class='ingredient-wrap'>
              <label class="form-text">食材・調味料</label>
            </div>
            <div class='ingredient-wrap'>
              <label class="form-text">分量</label>
            </div>
          </div>
            <% if @recipe.ingredient_names != [""] && @recipe.ingredient_names.present? %>
              <% @recipe.ingredient_names.each_with_index do |ingredient, i| %>
                <div class="ingredient-group ingredient-form">
                  <input type="text" name="recipe_form[ingredient_names][]", value="<%= ingredient %>", placeholder="食材・調味料", class="input-ingredient input", id="ingredient_name">
                  <input type="text" name="recipe_form[quantities][]", value="<%= @recipe.quantities[i] %>" , placeholder="分量", class="input-ingredient input", id="quantitity">
                </div>
              <% end %>
            <% else %>
              <div class="ingredient-group ingredient-form">
                <input type="text" name="recipe_form[ingredient_names][]", placeholder="食材・調味料", class="input-ingredient input", id="ingredient_name">
                <input type="text" name="recipe_form[quantities][]", placeholder="分量", class="input-ingredient input", id="quantitity">
              </div>
            <% end %>

          <%# 追加・削除をするためのフォームをJSで扱えるようにする %>
          <%= javascript_tag  do %>
            const ingredient =  
            `  <div class="ingredient-group ingredient-form">
            <input type="text" name="recipe_form[ingredient_names][]", placeholder="食材・調味料", class="input-ingredient input", id="ingredient_name">
            <input type="text" name="recipe_form[quantities][]", placeholder="分量", class="input-ingredient input", id="quantitity">
          </div>`
          <% end %>
          <div class="button-wrap">
            <button type="button" class="ingredient-button" id="button_plus">行を追加</button>
            <button type="button" class="ingredient-button" id="button_delete">行を削除</button>
          </div>
          
        </div>
        <%= f.submit "保存して閉じる" ,class:"popup-register-btn", id:"edit"%>
        <button type="button" class="batsu" id="close">×</button>
      </div>
    <% end %>
  </div>  
</div>

app/views/recipes/index.html.erb
<%= render "shared/header"%>

<div class="main">
  <div class="recipes">
    <% @recipes.each do |recipe| %>
      <div class="recipe">
        <% if recipe.image.attached? %>
          <%= image_tag recipe.image , class:"food-picture" if recipe.image.attached?%>
          <% else %>
          <%= image_tag "oishii2_man.png" , class:"food-picture"  %>
        <% end %>
        <div class="content">
          <%= link_to recipe.name, recipe_path(recipe) ,class:"title" %>
          <p class="ingredient">材料：
            <% recipe.ingredients.each do |ingredient|%>
              [<%= ingredient.ingredient_name %>]
            <% end %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render "shared/footer"%>

app/views/recipes/new.html.erb
<%= render "shared/header"%>

<%= form_with model: @recipe, url:content_recipes_path, class: 'registration-main new', local: true do |f| %>

<div class='form-wrap new'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      レシピのタイトル
    </h1>
  </div>

  <%= render 'shared/error_messages', model: @recipe %>  

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">レシピタイトル</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :name, class:"input-default", id:"name", placeholder:"レシピタイトルを入力してください", maxlength:"40" %>
  </div> 

  <div class='register-btn'>
    <%= f.submit "レシピ内容登録へ進む" ,class:"register-red-btn" %>
  </div>
</div>
<% end %>


<%= render "shared/footer"%>

app/views/recipes/search.html.erb
<%= render "shared/header"%>

<div class="main">

  <div class="result">
    <%= link_to "ホームに戻る", root_path, class:"link"%>
  </div>
  
  <div class="recipes">
    <% if @results.present? %> 
      <% @results.each do |result| %>
          <div class="recipe">
            <% if result.image.attached? %>
              <%= image_tag result.image , class:"food-picture" if result.image.attached?%>
            <% end %>
            <div class="content">
              <%= link_to result.name, recipe_path(result) ,class:"title" %>
              <p class="ingredient">材料：
                <% result.ingredients.each do |ingredient|%>
                  [<%= ingredient.ingredient_name %>]
                <% end %>
              </p>
            </div>
          </div>
      <% end %>
    <% else %>
      <div class="result">
        <p class="submit-result">検索された食材をつかうレシピはありません</p>
        <%= link_to "レシピをつくる", new_recipe_path , class:"link" %>
      </div>
    <% end %>
  </div>
</div>
<%= render "shared/footer"%>

app/views/recipes/show.html.erb
<%= render "shared/header"%>
<%# レシピの概要 %>
<div class="recipe-show">
  <div class="recipe-box">
    <h2 class="name">
      <%= @recipe.name %>
    </h2>
    <div class="options">
      <% if user_signed_in? %>
        <% if current_user.id == @recipe.user.id %>
          <%= link_to 'レシピの編集', edit_recipe_path(@recipe), class: "recipe-red-btn" %>
          <%= link_to '削除', recipe_path(@recipe), method: :delete, class:'recipe-destroy' %>
        <% end %>
      <% end %>
    </div>
    <div class='recipe-img-content'>
      <%= image_tag @recipe.image ,class:"recipe-box-img" if @recipe.image.attached? %>
    </div>
    
    <div class="recipe-ingredient">
      <p class="method">材料</p>
      <% @recipe.ingredients.each_with_index do |ingredient, i|%>
        <div class="ingredient-row">
          <p class="ingredient-name"><%= ingredient.ingredient_name %></p>
          <% ingredient.quantities.each do | quantity |%>
            <% if quantity.recipe_id == @recipe.id %>
              <p class="ingredient-quantitiy"><%= quantity.quantity %></p>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
    
    <div class="recipe-explain-box">
      <p class="method">作り方</p>
      <span><%= @recipe.description %></span>
    </div>  
  </div>
</div>
  <%# /レシピの概要 %>
<%= render "shared/footer"%>

app/views/recipes/submit.html.erb
<%= render "shared/header"%>

<div class="main">

  <div class="result">
    <%= link_to "ホームに戻る", root_path, class:"link"%>
  </div>
  
  <div class="recipes">
    <% if @ingredients.present? %> 
      <% @ingredients.each do |ingredient| %>
        <% ingredient.recipes.each do |recipe| %>
          <div class="recipe">
            <% if recipe.image.attached? %>
              <%= image_tag recipe.image , class:"food-picture" if recipe.image.attached?%>
            <% end %>
            <div class="content">
              <%= link_to recipe.name, recipe_path(recipe) ,class:"title" %>
              <p class="ingredient">材料：
                <% recipe.ingredients.each do |ingredient|%>
                  [<%= ingredient.ingredient_name %>]
                <% end %>
              </p>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <div class="result">
        <p class="submit-result">検索された食材をつかうレシピはありません</p>
        <%= link_to "レシピをつくる", new_recipe_path , class:"link" %>
      </div>
    <% end %>
  </div>
</div>

<%= render "shared/footer"%>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <p class="copy-right">Copyright© All Rights Reserved</p>
</div>

app/views/shared/_header.html.erb
<div class="header">
  <div class="header-left">
    <div class="app-name">
      <%= link_to "RecipeRator", root_path , id:"recipe-rator" %>
    </div>
    <div class="user-name">
      <% if user_signed_in? %>
        <p>ようこそ</p> 
      <% end %>
    </div>
  </div>
  
  <div class="search-form">
    <%= form_with(url: search_recipes_path, local: true, method: :get, class: "form") do |form| %>
        <%= form.text_field :keyword, placeholder: "料理名・食材名", class: "search" %>
      <%= form.submit "レシピ検索", class: "submit" %>
    <% end %>
    <%# 後に実装 %>
    <%# <div id="search-result"></div> %>
  </div>
  
  <div class="header-right">
    <div class="user">
      <% if user_signed_in? %>
        <div class="buttons">
          <%= link_to "ログアウト", destroy_user_session_path , method: :delete, class:"button logout-button" %>
          <%= link_to "ユーザー編集", edit_user_registration_path , class:"button logout-button" %>
          <%= link_to "レシピ登録", new_recipe_path , class:"button recipe-button" %>
        </div>
      <% else %>
        <div class="buttons">
          <%= link_to "ログイン", new_user_session_path, class:"button login-button" %>
          <%= link_to "ユーザー新規登録",new_user_registration_path, class:"button signup-button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_second_header.html.erb
<div class="top">
  <div class="user-functions">
    <ul class="user-menu">
      <li class="user-name"> 
        <% if user_signed_in? %>
          <p>ようこそ</p> 
        <% end %></li>
      <li class="user-function-link">
        <a id="user-menu-config" href="#" class="user-menu-link">
          <img alt="設定" src="">
        </a>
      </li>
    </ul>
  </div>
</div>